[package]
name = "cypher-in-png"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
clap = { version = "4.3.21", features = [ "derive" ] }
